### ISSUE TITLE
Bluetooth (adapter no needed)

### ISSUE THREAD

**Issue by MelisseCabral** [joaodematejr/S145-Hackintosh#1]
There are kext available to the board of this device.
Just install with OpenCore Configurator.

I also have problem with HDMI if got that fixed please let me know.
[Bluetooth.zip](https://github.com/joaodematejr/S145-Hackintosh/files/6208470/Bluetooth.zip)

**Comment by joaodematejr** [comment]
Thank you very much, I am looking for a solution for HDMI when I find a solution notice.
