### ISSUE TITLE
How to boot

### ISSUE THREAD

**Issue by Synctifyy** [joaodematejr/S145-Hackintosh#5]
how do i boot into this i can only pick ubuntu for som reason
![578or3u4v7y71](https://user-images.githubusercontent.com/82714233/140647379-faf6b990-ae25-4d30-b976-d53cb2e988ab.jpeg)
?

**Comment by joaodematejr** [comment]
the model is the s145 ? if you wanted to install only macos, delete the linux and windows partitions
